from handlers.about_bot_handler import about_router
from handlers.deepseek_handler import deepseek_router
from handlers.pravo_handler import pravo_router
from handlers.promo_handler import promo_router
from handlers.reaction_handler import react_router
from handlers.weather_handler import weather_router
