from handlers.bot_description import description_router
from handlers.gpt_router import gpt_router
from handlers.pravo_router import pravo_router
from handlers.promo_router import promo_router
from handlers.reaction_router import react_router
from handlers.weather_router import weather_router