from features.malicious_phrases import malicious_message, get_random_message
from features.open_weather import get_weather, get_wind_direction
from features.new_year import get_random_year_message, yearmessage