from features.phrase_service import automessage, get_random_message
from features.weather_service import get_weather, get_wind_direction
from features.year_service import get_random_year_message, yearmessage